config/routes.rb
Rails.application.routes.draw do


  resources :groups, :only => [:show, :create]
  resources :users, :except => [:edit]
  resources :friendships

  root :to => "pages#index"

  # AJAX-only endpoints
  post '/submit_position' => 'groups#submit_position'
  get '/submit_position' => 'groups#submit_position'
  get '/get_group_details' => 'groups#get_group_details'
  get '/get_group_coordinates' => 'groups#get_group_coordinates'


  post '/send_text' => 'send_text#send_text_message'

  get '/users/:id/edit' => 'users#edit', :as => 'users_edit'
  get '/users/:id/friends' => 'users#friends', :as => 'users_friends'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  validates :phone, :presence => true

  has_and_belongs_to_many :groups
  has_many :positions

  has_many :friendships
  # has_many :users, :source => :friendship, :through => :friendships
  has_many :friends, :through => :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authorize_user, :only => [:index]
  # before_action :check_for_user
  before_action :check_for_user, :except => [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    #Users who are friends excluding self
    @user = User.find params[:id]
    # @friendship = Friendship.where(user_id: params[:id])
    fids = @current_user.friendships.pluck(:friend_id)
    fids << @current_user.inverse_friends.pluck(:user_id)
    fids = fids.flatten!
    fids = fids - [@current_user.id]
    fids.uniq!
    @friendships = User.where('id in (?)', fids)

  end

  def friends

    #Users who are not friends excluding self
    fids = @current_user.friendships.pluck(:friend_id)
    fids << @current_user.inverse_friends.pluck(:user_id)
    fids = fids.flatten!
    fids = fids + [@current_user.id]
    fids.uniq!
    @strangers = User.where('id not in (?)', fids)
  end


  def edit

    @user = @current_user

  end

  def create
    @user = User.new (user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    @user = @current_user
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])

      @user.image = req["url"]
      if @user.update(user_params)
        redirect_to user_path
      else
        render :edit
      end

    else
      if @user.update(user_params)
        redirect_to user_path
      else
        render :edit
      end
    end
  end

  def destroy
    user = User.find params[:id]
    user.destroy
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :phone, :password, :password_confirmation, :image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
<div class = "row col-xs-10 col-xs-offset-1">
  <h2>Edit Profile</h2>

  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ol>
  <% end %>
<div>
<%= form_for(@user, :class => "form-horizontal", :html => {:multipart => true}) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <div>
      <%= f.text_field(:name, :class => "form-control", :autofocus => true, :required => true )%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <div>
    <%= f.text_field(:email, :class => "form-control", :required => true) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <div>
      <%= cl_image_upload_tag :image, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :Phone %>
    <div>
      <%= f.text_field(:phone, :class => "form-control", :required => true) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <div>
      <%= f.password_field(:password, :class => "form-control" )%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <div>
      <%= f.password_field(:password_confirmation, :class => "form-control" )%>
    </div>
  </div>

  <%= f.submit "Save", :class => "btn btn-primary"%>
<% end %>
</div>
</div>
</div>

app/views/users/friends.html.erb
<% for user in @strangers %>
  <div class="user">
    <p>
      <strong><%=h user.name %></strong>
      <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
      <div class="clear"></div>
    </p>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="col-xs-6 col-xs-offset-3">

<h2>Sign Up</h2>
<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control", :autofocus => true, :required => true %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, :class => "form-control", :required => true %>
</div>

<div class="form-group">
  <%= f.label :phone %>
  <%= f.text_field :phone, :class => "form-control", :required => true %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, :class => "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :class => "form-control" %>
</div>
  <%= f.submit "Sign up" %>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>
<%= image_tag @user.image, :class => "profileImg" %>

<p><%= link_to "Find Friends", users_friends_path %></p>


<h3>Your Friends</h3>
<!-- <ul>
  <% for friendship in @friendships %>
  <li>
    <%= h friendship.name %>
    (<%= link_to "remove", friendship, :method => :delete %>)
  </li>
  <% end %>
</ul> -->




<!-- /send_text?number_to_send_to=#{@current_user.phone} -->

<%= form_for Group.new do |f| -%>
<%= select_tag "friends", options_from_collection_for_select(@friendships, "id", "name", "1"), :class => 'selectlist', multiple: true %>
<%= f.text_field :name, :placeholder => 'Enter the name of group...' %>
<%= f.text_field :location, :placeholder => 'Enter the location...' %>
<%= f.datetime_select :datetime %>
<%= f.submit 'Broadcast', :class => 'broadcast' %>

<% end -%>


<!-- <%#= form_tag("/groups", method: :post) do -%>
<%#= select_tag "friends", options_from_collection_for_select(@friendships, "id", "name", "1"), :class => 'selectlist', multiple: true %>

<%#= text_field 'group[name]', nil, placeholder: 'Enter the name of group..' %>
<%#= text_field 'group[location]', nil, placeholder: 'Enter the location..' %>
<%#= select_datetime %>
<%#= submit_tag 'Broadcast', :class => 'broadcast' %>

<%# end -%> -->