config/routes.rb
Rails.application.routes.draw do


  resources :groups, :only => [:show, :create]
  resources :users, :except => [:edit]
  resources :friendships

  root :to => "pages#index"

  # AJAX-only endpoints
  post '/submit_position' => 'groups#submit_position'
  get '/submit_position' => 'groups#submit_position'
  get '/get_group_details' => 'groups#get_group_details'
  get '/get_group_coordinates' => 'groups#get_group_coordinates'


  post '/send_text' => 'send_text#send_text_message'

  get '/users/:id/edit' => 'users#edit', :as => 'users_edit'
  get '/users/:id/friends' => 'users#friends', :as => 'users_friends'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trackpal</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />


</head>
<body>

  <nav class="navbar navbar-inverse">
  <ul class="nav navbar-nav">
  <% if @current_user.present? %>

    <li class="active"><%= link_to 'Home', user_path(@current_user) %></li>
    <li><%= link_to "Logout #{ @current_user.email }", logout_path, :method => :delete %></li>
    <li><%= link_to "Change Profile", users_edit_path(@current_user) %></li>
  <% else %>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Sign up', new_user_path %></li>

  <% end %>
  </ul>
</nav>

<%= yield %>

</body>
</html>